name = "website"
version = "0.1.0"
defaultTargets = ["build-site"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.33.0"

[[lean_lib]]
name = "Site"

[[lean_exe]]
name = "build-site"
root = "Main"
